name: Update Game Screenshot
on: [push]
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Take screenshot
      uses: hudell/screenshot@v1
      id: screenshot
      with:
        url: https://warregeerts.github.io/Prog4_GeertsWarre/index.html
        
    - name: Save & commit
      run: |
        mkdir -p screenshots
        mv screenshot.png screenshots/game.png
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add screenshots/game.png
        git commit -m "Update game screenshot [skip ci]" || exit 0
        git push
